#!/bin/bash
#
#Backup programm
#
echo "Sisesta kataloogi asukoht: "
read kataloog
nimi="$(basename $kataloog)"
echo "$nimi"
tar -zcf $nimi.backup.tar $kataloog/
gzip $nimi.backup.tar
mkdir /home/user/skriptimine/praks4a/backup
mv $nimi.backup.tar.gz /home/user/skriptimine/praks4a/backup/$nimi.backup.tar.gz
echo "Kataloogi $kataloog  backup_i nimi on $nimi.backup.tar.gz"
echo "ja ta asub /home/user/skriptimine/praks4a/backup/ kataloogis."
#
