#!/bin/bash
#
# kellaaja ja kuupäeva skript
echo -n "Today is " #kirjutab Today is
date +"%A, %B %d, %Y" #kirjutab praeguse päeva, kuu, kuupäevaliselt päeva ja aasta
echo -n "Time is " #kirjutab Time is 
date +"%H:%M" #tekitab kellaaja (Tunnid:Minutid)
echo -n "Calendar of " #kirjutab Calendar of
cal #tekitab kalendri
#
#
