#!/bin/bash
#
# Otsimise skript
#
find /var -type f -name "*.log" 2>/dev/null -exec wc -l {} + | sort -rn #leiab  kõik failid mis lõppevad .log, loeb kokku read ja sorteerib nad kahanemisjärjekorras
#
# skripti lõpp
