#!/bin/bash
#
#Bussi Korraldaja abi
#
echo -n "Sisestage reisijate arv grupis: "
read reisijate_arv
echo -n "Sisestage bussis olevate kohtade arv: "
read bussikohad

Bussarv=` expr $reisijate_arv \/ $bussikohad`
Mahajaanud=` expr $reisijate_arv \- $Bussarv \* $bussikohad`
sleep 1
echo "Täielikult täidetud busse on $Bussarv."
sleep 1
echo "Maha jääb täis olevatest bussidest $Mahajaanud inimest."
#
